#! /bin/sh
chmod -x *.pdf *.jpg *.ltx bidi.dtx
xelatex -shell-escape bidi.dtx
xelatex -shell-escape bidi.dtx
xelatex -shell-escape bidi.dtx
xelatex -shell-escape bidi-doc.ltx
xelatex -shell-escape bidi-doc.ltx
xelatex -shell-escape bidi-doc.ltx
mkdir -p doc/latex/bidi source/latex/bidi tex/latex/bidi 
mkdir bidi
mv *.sty *.cls *.def  bidi.tex bidi-bibitem.pdf bidi-logo.pdf tex/latex/bidi
mv *.pdf *.jpg *.tex README  doc/latex/bidi
mv *.ltx bidi.dtx bidi.ins source/latex/bidi
zip -r bidi-tds doc/latex/bidi source/latex/bidi tex/latex/bidi 
mv bidi-tds.zip bidi.tds.zip
mv doc/latex/bidi/*.pdf doc/latex/bidi/*.jpg doc/latex/bidi/README source/latex/bidi/*.ltx source/latex/bidi/bidi.dtx tex/latex/bidi/bidi-bibitem.pdf bidi
zip -r bidi bidi.tds.zip bidi
rm -r doc source tex bidi
rm *.idx *.out *.toc *.ilg *.ind *.hd *.aux *.log bidi.tds.zip